# Generated by Django 4.1.4 on 2023-03-31 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geo_park', '0002_remove_subuser_subscription'),
    ]

    operations = [
        migrations.AddField(
            model_name='subuser',
            name='subscription',
            field=models.CharField(choices=[('1', 'Начинающий тариф'), ('2', 'Оптимальный тариф'), ('3', 'Продвинутый тариф')], default='2', max_length=1, verbose_name='Подписка'),
        ),
    ]
