# Generated by Django 4.1.4 on 2023-04-19 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geo_park', '0003_subuser_subscription'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=55, verbose_name='Имя')),
                ('is_active', models.BooleanField(verbose_name='Активность')),
            ],
        ),
    ]
