# Generated by Django 4.2.1 on 2023-05-16 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geo_park', '0004_testmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyImageModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='geo_entity_pic')),
                ('data', models.CharField(max_length=500)),
            ],
        ),
        migrations.AlterModelOptions(
            name='categoriesnews',
            options={'verbose_name': 'Категория новостей', 'verbose_name_plural': 'Категории новостей'},
        ),
        migrations.AlterModelOptions(
            name='editimage',
            options={'verbose_name': 'Обработка изображения', 'verbose_name_plural': 'Обработка изображений'},
        ),
        migrations.AlterModelOptions(
            name='generaluser',
            options={'verbose_name': 'Гость', 'verbose_name_plural': 'Гости'},
        ),
        migrations.AlterModelOptions(
            name='news',
            options={'verbose_name': 'Новость', 'verbose_name_plural': 'Новости'},
        ),
        migrations.AlterModelOptions(
            name='subuser',
            options={'verbose_name': 'Пользователь', 'verbose_name_plural': 'Пользователи'},
        ),
        migrations.RemoveField(
            model_name='editimage',
            name='image_user',
        ),
        migrations.AddField(
            model_name='editimage',
            name='img_user_base64',
            field=models.TextField(default=1, verbose_name='Base64'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='editimage',
            name='name_photo_user',
            field=models.CharField(default=1, max_length=155, verbose_name='Наименование фотографии пользователя'),
            preserve_default=False,
        ),
    ]
